name: Build and Push Dist

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test

            - name: Build package
              run: npm run build

            - name: Commit and push dist folder
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add dist/
                  git diff --quiet && git diff --staged --quiet || git commit -m "Build: Update dist folder [skip ci]"
                  git push
