name: Build and Release

on:
    push:
        branches: [main]
        tags: ["v*"]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/')

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test

            - name: Build package
              run: npm run build

            - name: Commit and push dist folder
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add dist/
                  git diff --quiet && git diff --staged --quiet || git commit -m "Build: Update dist folder [skip ci]"
                  git push

    release:
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/v')

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test

            - name: Build package
              run: npm run build

            - name: Commit and push dist folder
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add dist/
                  git diff --quiet && git diff --staged --quiet || git commit -m "Build: Update dist folder for release [skip ci]"
                  git push

            - name: Create Release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  body: |
                      ## What's Changed

                      This release includes the latest updates to the Palau CSV to JSON wrapper.

                      ### Features
                      - Enhanced CSV parsing with header validation
                      - Support for blank and duplicate header handling
                      - TypeScript support with full type definitions

                      ### Installation
                      ```bash
                      npm install PalauProject/PalauCsvToJsonWrapper#v${{ github.ref_name }}
                      ```

                      ### Usage
                      ```typescript
                      import { PalauCsvToJsonWrapper } from 'palau-csvtojson-wrapper';

                      const wrapper = new PalauCsvToJsonWrapper();
                      const result = await wrapper.fromString('name,age\nJohn,25\nJane,30');
                      ```
                  draft: false
                  prerelease: false
